- README.md
> Update grammar and spelling

- Xadrez.md
> Update from (https://www.loadwallet.org) to (https://www.loafwallet.org)

- Xadrez.md
> BTCPay twitter link update

- Managed.md
- README.md
As discussed in Slack, adding the managed BTCPay servers to the docs.
> Managed btcpay

- Managed.md
- Support.md
> added website

- FAQ.md
I've been following people questions about BTCPay for a few months now. While GitHub is probably not the best way in which we can provide good FAQ and documentation for people not familiar with GitHub, I wanted to leave it here so that others can build on it and improve it. 
I re-arranged the FAQ and added .bit more generic questions, followed by technical issues.
I'm leaving it here, and I plan to work on it a bit more with the help of others.
There are two sections in particular which need to be reviewed : 
1. "Network Cost"
2. "Minimal Requirments"
I am not confident I got those two right, so please take a closer look at them and suggest or do the changes.
> Updating FAQ

- FAQ.md
I read again the FAQ, and it seemed to me that some places were a bit redundant, or not very clear, especially in the more general questions at the beginning. I tried to eliminate redundancy and improve what could be, tell me what you think.
> [doc] eliminates some redundancy in FAQ, minor improvements

- FAQ.md
- README.md
Minor changes to the documentation and readme. 
- Adding links to new web-installation to both readme and faq
- re-arranging content in the FAQ that easy questions are on top, technical questions at the bottom of the FAQ
- removed merchant's guide from the top of the FAQ added a new section at the bottom "Additional Resources" where I added Nbitstack, Slack and 
- Expanded integrations into readme
- Added btcpay wiki into readme
Please review, make sure it's synced properly with most recent updates.
> Updating read.me, FAQ and docs

- README.md
> Updated broken url link

- UseCase.md
> Updating UseCase.md

- ThirdPartyHosting.md
I don't know if this is the right procedure to ask to add our service to the list so please let me know if it's inappropriate (I'm on the slack to chat)
> Added nodl.it (aka lightning-solutions.eu)

- TryItOut.md
Add a list of demo stores, pos for people to try out.
> Add BTCPay Demo to TryItOut.md

- GettingStarted.md
Fixing minor typo and adding a link to an excellent video about why is sync important and why it takes time.
> Typo fix and adding aantonop video link

- ThirdPartyHosting.md
> add third party hoster

- UseCase.md
I have some suggestions for the structure of the "Use Cases" page : 
* I feel it is more about "Value proposition" for users (principally merchants) and "opportunities" for other actors of the ecosystem to build upon BTCPay, so I reorganised the page in two sections and renamed it to "valueproposition.md" for short
* I added some more thoughts about why it is bad to reuse address, which is a strong argument in favor of BTCPay
* I made some minor editing for style
What do you think ?
> Suggestions for "Use Case" page

- SUMMARY.md
Adds new document into summary.md and re-orders the links slightly to make everything more user-friendly.
> Add Walkthrough.md to Summary.md

- HardwareDeployment.md
> Added HardwareDeployment.md

- WooCommerce.md
Adds store pairing section with a video.
> Add Store Pairing to WooCommerce.md

- HardwareDeployment.md
I added a few things related to SSH and change a little wording here and there.
> Updated SSH Part

- Troubleshooting.md
Work in progress. Requires someone to review and add content in **section 2. Logs.**
This PR should close #48 once it's reviewed by someone who can add more information to the logs section.
1. I am not sure if we have BTCPay Specific logs
2. Logs for Bitcoin Core? Are they necessary?
3. I covered LN logs quite in-depth but it's based on my personal experience, so a dev should review those.
I know a document like this won't stop users from asking questions, but **maybe**  they will be able to formulate questions better and provide clearer information for the community to solve.
Feel free to modify edit and remove whatever you wish. Final proof-reading should be done before merging everything.
> [WIP] Add Troubleshooting.md

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
This PR adds FAQ-Deployment.md which contains solutions to commonly asked deployment questions.
> FAQ-Deployment

- FAQ/FAQ-Apps.md
- FAQ/FAQ-General.md
- FAQ/readme.md
This add a FAQ for Apps with only a few questions so far that should be expanded in future.
Update broken links in readme.
> Add FAQ-Apps

- FAQ/FAQ-ServerSettings.md
Adds a page with frequently asked questions and common issues about Server Settings elements. Updates, Customizaiton, SSH, etc.
> Add FAQ-ServerSettings.md

- FAQ/FAQ-ServerSettings.md
- FAQ/FAQ-Stores.md
- FAQ/readme.md
- SUMMARY.md
This PR adds new file FAQ-Stores.md.
This is an important addition, since it can be used for [Tooltips in UX.](https://github.com/btcpayserver/btcpayserver/issues/382)
I did my best to cover all of the important options. That said, since these settings are important for merchants and can cause problems if adjusted inappropriately, I would like to ask for someone to review and make sure I did not explain something inaccurately.
Please feel free to make any necessary edits. I'm fine with that.
PR : 
1. Creates FAQ-Stores.md
2. Adds FAQ-Stores.md to Summary.md
3. Updates and re-arranges FAQ/readme
> Add FAQ-Stores.md, re-arrange FAQ-readme, Summary.md

- FAQ/FAQ-Altcoin.md
Adds altcoin.md with common questions.
> Add FAQ-Altcoin.md

- FAQ/readme.md
- SUMMARY.md
This is my final PR that closes the huge FAQ re-structure.
> Update Readme, Summary, MD

- Deployment.md
Adding Deployment document: Ref #101 
If there are other ways I missed I can add them. Also tables don't look very good on mobile, not sure if that matters, I can change it. @bitcoinshirt it contains a link to the FAQ page for minimum requirements. I can link to the new FAQ file if/when you move it.
> Add Deployment.md

- Translate.md
Fix curly braces for GitBook view.
> Fix format in Translate.md

- FAQ/FAQ-Apps.md
- FAQ/readme.md
- Adds theme.md to readme.
- Adds "how to customize POS" in FAQ-Apps
- Adds links in readme APPS
- Adds forgotten payment button to readme
> Add Theme.md to readme, FAQ

- Deployment.md
1. Update ARM32v7 link to BTCPay Docker
Link shows which version is supported. 
2. Add Fast Sync Link
Link to FS Readme.
> Update hardware build links

- BTCPayVsOthers.md
- ComparePaymentProcessors.md
Draft of #57:
- Compare BTCPay as a payment processor
- Explain processor trade-offs
- Link BIP70 converter
Reasons:
I made a chart to compare processors. Some of the websites make some claims I thought were not true (mostly for KYC and middleman). So I updated the table, but then it goes against what they advertise so I also don't want to get sued for defamation.... so instead of putting their names in a table, I just identify them by what they do.
> Payment processor comparison

- README.md
> Fix typo in TOC '[BTCPay vs other processors]'

- FAQ/FAQ-Wallet.md
- Walkthrough.md
This one requires a review. I really tried to get a good grip on it, but not sure if I covered it all and explained it clearly. Edits are welcome. I think it probably needs better explanation.
@NicolasDorier please review
Closes #83
> Add Wallet Re-Scan

- SUMMARY.md
- Wallet.md
The goal of wallet.md is to present an internal BTCPay as a feature and explain it's function.
> Create new document Wallet.md

- RaspberryPiDeployment.md
Raspberry Pi with Pruning and FastSync
> Add RaspberryPi Instructions

- FAQ/FAQ-Stores.md
Explains the network fee to reflect the newest options. Fixed minor typos and structured better.
Close #151
> Update Network fee

- Accounting.md
Ping @britttttk and @bitcoinshirt is it clear?
> Document export fields

- Apps.md
- BTCPayVsOthers.md
- README.md
- UseCase.md
PR addresses issue #158 
See commit notes for details.
> Crowdfunding update

- FAQ/FAQ-Apps.md
- FAQ/readme.md
This PR closes #166 and fixes few typos along the way.
> [WIP} Document WooCommerce and Crowdfunding Integration

- FAQ/FAQ-Integrations.md
- FAQ/readme.md
> Document WooCommerce non-standard orders

- RaspberryPiDeployment.md
Pi needs increase in swapsize, best to have swapfile on external media instead of SD card.
> Added swapfile instructions

- LightningNetwork.md
> fix grammar

- LunaNodeWebDeployment.md
Be more descriptive since this is a very popular introductory document for users.
> Improve web deployment description

- Deployment.md
- FAQ/FAQ-Deployment.md
> fix link for min. reqs. & nits

- README.md
Add community article for alternative deployment method.
> Digital Ocean deployment article

- README.md
Add AWS EC2 deployment community article.
> Add AWS Community Article

- Deployment.md
Update Deployment.md doc
- Add Digital Ocean / Amazon AWS (Not sure how it will look on GitBook..)
- Add OpenVZ disclaimer
> Add VPS deployment options

- FAQ/FAQ-Synchronization.md
> Add Fast Sync video to FAQ

- LocalDevelopment.md
> bump sdk and add links

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
This is a proposal to solve issue #198.
In my view, there are 2 goals:
* explain how to activate Tor
* make it clear that it is not intended as a privacy and/or security scheme, but more like an improvement of the setup that would allow to run BTCPay on environment where it would have been hard otherwise because of some network requirements (as Nicolas has explained in a Medium article about this topic)
I think that it's enough to answer those 2 questions separately in the FAQ. I think the "General Deployment" FAQ was the more appropriate.
Please let me know if I got something wrong, or if the message could be made even more clear.
> General deployment faq/tor

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
A simple proposal for the FAQ based on @JeffVandrewJr answer to issue #214
> General deployment faq/del opt

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
> Add FAQ-GeneralDeployment Question

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
> Add existing node Q to FAQ

- FAQ/FAQ-ServerSettings.md
- FAQ/readme.md
#230 
Skipped images because imo it's easy/obvious how to use this feature.
> add file storage to FAQ

- README.md
I just proofread and made some minor grammar and spelling corrections to the Read.md first page
> Minor Grammar & Spelling Corrections to Readme.md

- FAQ/FAQ-ServerSettings.md
> Update Server Settings FAQ with new theme.md instructions

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
Tor has been made activated by default, this document how to disable it
> Document how to disbale tor

- Accounting.md
> fix broken link

- FAQ/FAQ-ServerSettings.md
Temp links are working with FileSystem :)
> remove FileSystem note

- FAQ/FAQ-Stores.md
- FAQ/readme.md
> add disable invoice email FAQ

- ThirdPartyHosting.md
I added btcpayprovider.com to the list of BTCPay third-party hosts.
> Add Third-Party Hosting on the DOCS list

- FAQ/FAQ-Deployment.md
Added FAQ item "Can I use an existing Nginx server as a reverse proxy with SSL termination?"
> Added FAQ item "Can I use an existing Nginx server as a reverse proxy with SSL termination?"

- BTCPayVsOthers.md
howtoacceptcrypto.com website do not exist anymore (Dead for more than a week at least)
> howtoacceptcrypto.com do not exist anymore

- CreateStore.md
- RegisterAccount.md
This PR is part 1 of the #252.
It adds two files RegisterAccount. md and CreateStore.md and does not alter anything in the existing docs.
Once this part is merged, we should tackle:
**Part 2**, which will add ConnectWallet.md, LedgerNanoS.md.
**Part 3** should connect all pieces together, by altering summary.md, removing unnecessary parts of the GettingStarted.md and updating the readme. It will also nest all the wallets into "Connecting a wallet" section.
**Part 4** should tackle payment testing and "What to do next" (What to do next section is yet to be discussed.)
Once all of the planned pull-requests get merged, we should be able to finish  #252 #267 #281 #213
> Doc Re-Structure Part 1 - RegisterAccount and CreateStore.md

- ManualDeploymentExtended.md
> Fix emojis for GitBook

- FAQ/FAQ-Stores.md
- FAQ/readme.md
Issue #273
There is probably a more exact reason. @pavlenex do you know?
> Add delete invoices to FAQ

- FAQ/FAQ-Stores.md
Link to this awesome invoice filtering doc in the delete invoices FAQ. #291 Good suggestion @NicolasDorier
> Add filtering invoices to delete invoices FAQ

- Apps.md
closes #296
Not sure if it needs an FAQ. It's pretty clear how it works when they add a product/perk.
> Mention the inventory feature in apps.

- FAQ/FAQ-Deployment.md
- FAQ/FAQ-Synchronization.md
> Add FastSync steps to Sync FAQ

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
> Add FAQ connect to 8333

- FAQ/FAQ-Stores.md
Closes #293 
Invoices.md seems fine as it is.
> Clarify confirmed vs completed status

- FAQ/FAQ-ServerSettings.md
- FAQ/readme.md
#295 
- Updated forgot password FAQ
- Added U2F & 2FA disable for user FAQ
> Add admin scripts to FAQ

- ColdCardWallet.md
- ElectrumWallet.md
This is just a part of already large PR #252 #241 
I'll add PSBT video soon, don't merge yet please, opened to feedback/review.
> Add ColdCard instructions + PSBT

- LedgerWallet.md
This is another wallet documentation for #252 
Once this one is merged, we only have to create ConnectWallet.md which lists all recommended wallets and links to their respective tutorials before we can finally close this huge restructuring issue.
> Add LedgerWallet.md

- TryItOut.md
> Update and extend Try It Out

- RaspberryPiDeployment.md
> Document domain setup

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
> Add FAQ - How to change to testnet

- README.md
Closes #319 
Probably needs some more work and maybe a nice metaphor only @NicolasDorier can think of.
Feedback/Edits/Reviews welcome.
> Update Readme.md with "Beyond Payment Processing"

- PrestaShop.md
The link pointed to a very old version of the PrestaShop plugin.
> Updated the PrestaShop.md

- FAQ/FAQ-Deployment.md
- FAQ/FAQ-Synchronization.md
1. FAQ-Deployment (line 86)
The newly formatted and initiated drive needs to be mounted before the setup process. Otherwise the docker data will be written onto the SD/eMMC card. 
2. FAQ-Synchronization
Rather than deleting the whole '_data' folder, only the 'blocks' and 'chainstate' folders should be deleted and recreated to reindex a node.
> Additions in Deployment and Synchronization FAQ

- AzureDeployment.md
- FAQ/FAQ-General.md
Closes #300 as far as docs are concerned.
> Remove mention of Azure as easiest way to deploy

- FAQ/FAQ-LightningNetwork.md
- FAQ/readme.md
This PR documents how to see LN version from cli or on the front end. It's useful when people are reporting issues in LN repositories and are asked to provide the version among many other things (checking vulnerability etc).
Closes #337
> Document how to see the LN version

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
Documents how to access .onion address without visiting clearnet. Discovered by norm, I am just documenting it.
Closes #258
> Document accessing .onion without clearnet

- RPi3.md
- RPi4.md
> Add domain setup to new RPI pages

- RPi3.md
- RPi4.md
This adds the ufw-related things I talked about in #328.
Also threw in some more whitespace clean ups here – hope these are pretty uncontroversial :)
> Extend firewall docs for RPI pages

- Apps.md
- ElectrumWallet.md
- WhatsNext.md
WIP for #313 
Needs table of contents for all use cases. Not sure if the gifs are too much for this doc.
> Update whatsnext.md and apps.md

- WhatsNext.md
> Add LibrePatron and Transmuter

- README.md
[#1131](https://github.com/btcpayserver/btcpayserver/pull/1131)
> Adds new supporter to readme

- README.md
Adds new supporter to readme.
This does not fix a gitbook preview unfortunately, there's something wrong with their tables and I submitted a ticket with them to see why GitBook does not render tables properly.
> Add supporter to readme

- FAQ/FAQ-Apps.md
> Additional hosts ssl

- LedgerWallet.md
@pavlenex here the updated extended info for the manual ledger setup
> feat(leadger): add more info to manual setup #357

- README.md
Picture will be visible once [#1174 ](https://github.com/btcpayserver/btcpayserver/pull/1174)merged
> Add new supporter to readme docs

- FAQ/FAQ-Synchronization.md
> Stop external node

- PrestaShop.md
Updates and expands docs prerequisites since current one causes [confusion](https://twitter.com/FractalEncrypt/status/1205172504815448064)
> Update PrestaShop.md prerequisites

- ElectrumWallet.md
- ElectrumX.md
- README.md
- SUMMARY.md
> Separate Electrum and ElectrumX docs, add P2SH to Electrum

- WasabiWallet.md
This PR adds minor improvements to Wasabi documentation when connecting to BTCPay's full node.
> Update Wasabi BTC-P2P terminology

- RPi4.md
They were too technical( and dangerous as you gave users terminal commands that formatted any drive) and only targeted Mac. I've extracted some from the official pi docs and expanded slightly.
> Update RPI 4 flashing to SD card docs

- FAQ/FAQ-Stores.md
- FAQ/readme.md
- Walkthrough.md
> Add change exchange rate to faq

- SUMMARY.md
Closes #407 
As discussed in #355
> Add SSH tunnel to summary.md

- FAQ/FAQ-Deployment.md
Add uninstall method for docker version
> Update FAQ-Deployment.md - add Uninstall BTCPay Server (docker version)

- Invoices.md
Add confirmed invoice status to invoices page for issue [#1288](https://github.com/btcpayserver/btcpayserver/issues/1288)
> Add confirmed invoice status

- Altcoins.md
- LocalDevelopment.md
- ManualDeployment.md
- ManualDeploymentExtended.md
Fix #349
Update .NET Core version and some Visual Studio mentions of 2017 to 2019.
> Update .net core references

- ThirdPartyHosting.md
I'm running a bitcoin node using BTCPay: kendesu.io
It is free. I just want to support bitcoin and the BTCPay project. I'm new to all of this, so please feel free to contact me with suggestions.
> Add third-party host

- Wallet.md
Closes #241 
Also removes unnecessary information for wallets and instead provides external links to guides.
> Update Wallet.md with Vault, PSBT, HD Key and minor formatting

- Altcoins.md
Just noticed a certain integration for UFO coin has not been added to the list, so adding it.
> Add UFO to the list

- Altcoins.md
Reverts btcpayserver/btcpayserver-doc#430
UFO was disabled on purpose with a comment
`// Disabled because of https://twitter.com/Cryptopia_NZ/status/1085084168852291586`
> Revert "Add UFO to the list"

- UseCase.md
There has been a lot of clutter in this document that made it look more like an article than a documentation. Removed the blablah text, formatted a bit better and added a new use-case (individual).
Probably there's still some work to be done to perfect this doc, so suggestions are welcome.
> remove clutter, add individual use case, formatting in UseCase.md

- RPi4.md
This implements [the workaround](https://github.com/btcpayserver/btcpayserver-docker/issues/263#issuecomment-581472247) for new deployments
> Prevent people from running into issue #263

- FAQ/FAQ-Deployment.md
no content changes.
only moving things around
> group 5xxx nginx errors + update table of context

- FAQ/FAQ-Deployment.md
The initial way it was documented had the following downside:
* Was using symbolic link, which make `docker volumes ls` unhappy
* Did not documented how to find the name of your drive
* Did not documented how to format the drive
* Did not documented how to make sure that docker start after the drive is ready
> Document better way of setting up docker volumes on different drive

- FAQ/FAQ-Deployment.md
- FAQ/readme.md
#199 
I just copy-pasted @Kukks's post and removed redundant stuff and added a bit of formatting.
> Adv "How to deploy BTCPay with my existing Bitcoin node (docker) to FAQ

- FAQ/FAQ-ServerSettings.md
- FAQ/FAQ-Stores.md
- FAQ/readme.md
> Address update issues and git-reset

- FAQ/FAQ-ServerSettings.md
> Generic ssh example

- Payjoin-spec.md
Ping @Kukks 
This is not for merge yet, this may change until we finished it.
> Add payjoin specification

- HotWallet.md
- ThirdPartyHosting.md
#481 Add hot wallet considerations to ThirdPartyHosting.md since it is related to the upcoming Payjoin feature release. 
- Explain why a host might keep this disabled.
- Explain user risks if it is enabled.
> Add hot wallet info to ThirdPartyHosting.md

- Payjoin-spec.md
We were not properly documenting the risks inherent to payjoin.
> Add payjoin risks

- FAQ/FAQ-Wallet.md
Wording, spelling ans such on the FAQ-Wallet.md file.
Reviews and change requests appreciated, if needed.
> FAQ-Wallet.md - Wording, spelling and such.

- FAQ/FAQ-Synchronization.md
Wording, spelling and such on FAQ-Synchronization.md
> FAQ-Synchronization.md - Wording, spelling and such.

- Payjoin-spec.md
the link to BIP79 is actually to BIP179
> fix wrong link

- Magento.md
Follow the quick-start guide here.
> fixed broken url link

- Accounting.md
> Accounting.md proofread

- docs/README.md
Forgot we have to readme files now 😭 
#517
> Add logos to the docs readme (introduction page)

- docs/.vuepress/styles/index.styl
- docs/README.md
Also improves the table border styles in general. Closes #526.
> Improve supporters table

- docs/.vuepress/styles/index.styl
Some adjustments to make the mobile version look and behave better.
> Mobile search improvements

- docs/FAQ/FAQ-Deployment.md
> Add opt-unsafe-expose to 8333 FAQ

- docs/Invoices.md
Closes #540 Add marked & additional statuses.
> Add more statuses and marked info

- package-lock.json
- package.json
Fixes hot reloading, [details here](https://github.com/vuejs/vuepress/issues/2392#issuecomment-633399465).
> Add temporary watchpack fix

- docs/ThirdPartyHosting.md
* Added Directory link to hosts instead of the host list.
Relates and closes #547 
* Fixed typos and such.
* Standardization of the "BTCPay Server" usage instead of "BTCPay" to content daddy Nick.
Note: I did not touch the titles, as to not potentially break the multiple links to this file.
> Added Directory link + typos and such.

- docs/.vuepress/config.js
First PR with me messing with config.js
Moves ElectrumX and EPS from "Electrum Wallet" to "Docker Plugins" as requested in #564
Reviews appreciated.
Closes #564
> Move ElectrumX and EPS from "Electrum Walllet" to "Docker Plugins"

- docs/CustomIntegration.md
Make the documentation a bit more inclusive :)
> Fix grammar and pronouns

- docs/.vuepress/styles/index.styl
Fixes #578. Thanks @pavlenex for spotting that! 👀
> Fix h5 and h6 headings size

- docs/.vuepress/preprocessMarkdown.js
- docs/.vuepress/preprocessMarkdown.spec.js
> Ensure newline before video HTML

- README.md
- setup-deps.sh
@britttttk mentioned some trouble with the setup script. This was related to it not being fully Windows compatible and also not supporting spaces in the file paths. Hopefully this fixes it – works for me using the Git Bash in an Windows VM.
> Setup: Windows compatibility

- docs/ReverseSSHtunnel.md
> use ssh-copy-id instead of doing things by hand

- docs/FAQ/FAQ-General.md
- docs/FAQ/README.md
* Adds "What if I have a problem with a paid invoice?" page title, question and answer in FAQ-general.
* Adds "What if I have a problem with a paid invoice?" question in FAQ-readme summary.
Closes #597
> Adds "What if I have a problem with a paid invoice?"

- docs/FAQ/FAQ-General.md
@britttttk 's suggestion in #598 wasn't commited when the PR was merged.
See here: https://github.com/btcpayserver/btcpayserver-doc/pull/598/files#r444315970
This PR fixes that missing commit.
> Missing commit for FAQ-general

- docs/.vuepress/config.js
- docs/GreenFieldExample.md
Usage example documentation for Greenfield
> Add greenfield usage example

- docs/FAQ/FAQ-Synchronization.md
> Pruning note in existing datadir FAQ

- docs/FAQ/FAQ-Altcoin.md
- docs/FAQ/README.md
> Altcoin faq cleanup

- docs/.vuepress/config.js
- docs/PullPayments.md
- docs/Refund.md
* Transfers the `create refund` § from Pullpayments.md to Refund.md
* Fixes typos and adds spacing for clarity in PullPayments.md
* Adds sentence in PullPayments.md directing to Refund.md
* Adds Refund.md - Used the § on the blog post featuring the v1.0.5.2
* Adds spacing between wording and images in the transferred §
* Nests Refund.md under PullPayments.md in config.js
Closes #605
> Adds Refund.md & changes PullPayments.md

- docs/FAQ/FAQ-General.md
- docs/FAQ/README.md
> Add API question to General FAQ

- docs/FAQ/FAQ-Apps.md
- docs/FAQ/README.md
> Update Apps FAQ

- docs/FAQ/FAQ-Deployment.md
- docs/FAQ/README.md
Most changes are from moving questions from general to manual deployment section.
> update deployment faq

- docs/FAQ/FAQ-Stores.md
Related #504 
Nothing much to fix here imo, I just rewrote the "invoice deleting" section. 
If someone notices more stuff to be cleaned in Stores-FAQ, let me know.
> Update Stores FAQ

- docs/FAQ/FAQ-LightningNetwork.md
- docs/FAQ/README.md
Mainly fixing spelling and making answers more clear. Part of #504.
> Update lightning FAQ

- docs/FAQ/FAQ-Synchronization.md
- docs/FAQ/README.md
Basically spelling and nit fixes only. Part of #504
> updates to sync faq

- docs/ReverseSSHtunnel.md
Mostly formatting, but this makes the code snippets syntax highlighted and easily copyable. Also highlights the warning and formats the additional resources.
> Improve reverse ssh docs

- docs/FAQ/FAQ-Integrations.md
- docs/FAQ/FAQ-Synchronization.md
- docs/FAQ/README.md
Link fixes and hide php. Part of #504
> Update integrations faq

- docs/FAQ/FAQ-ServerSettings.md
- docs/FAQ/README.md
nits: spelling, updating question format. Part of #504
> Update Server Settings FAQ

- docs/FAQ/FAQ-General.md
- docs/FAQ/README.md
- non SegWit wallet issue
- paying from exchange
Closes #599
> Add problem paying invoice question to FAQ

- docs/FAQ/FAQ-General.md
- docs/ThirdPartyHosting.md
Closes #583 
- Updates for hot wallets and 
- more detailed address-reuse FAQ answer.
> Updates to private key and address re-use faq questions

- .github/workflows/build.yml
- package-lock.json
- package.json
Output is limited to broken links and the build step allows failure, so that false positives do not halt the entire build.
> Improve linkcheck step in build

- docs/FAQ/FAQ-Stores.md
- docs/FAQ/README.md
> Add 0 invoice to faq with use cases

- docs/.vuepress/config.js
- docs/.vuepress/styles/btcpayserver-main.styl
- docs/.vuepress/styles/index.styl
Addressing the problems mentioned in #628. Let's keep the discussion in the issue. /cc @Zaxounette
> Search improvements

- docs/.vuepress/styles/index.styl
- docs/AzurePennyPinching.md
Just some improvements I noticed.
> AzurePennyPinching: Fix typos and update formatting

- docs/DynamicDNS.md
Just some improvements I noticed.
> DynamicDNS: Fix typos and update formatting

- README.md
- docs/README.md
> Supporters: Display in two rows

- docs/.vuepress/styles/index.styl
- docs/README.md
Some more improvements I didn't get to in yesterdays PR.
No table cell border and better responsive display.
> Improve supporters styles

- docs/BTCPayVsOthers.md
This PR hopefully closes #637
* Various typo fixes, and namely fixes BTCPay Server incompleteness for standardization.
* Adds missing title in summary (Can't find this info for other payment processors) and adds new one (Censorship Resistance)
* Refreshes 'Features' section:
This section requires review, as i'm not sure if it fits what the issue asked for.
So many features and informations while trying to keep that section clean and tidy presents a challenge.
* Rewording of the 'Fiat' section to include Transmuter info. & link.
* Adds Tor and Payjoin Support to the 'Privacy' section.
* Adds simple censorship resistance section an § based on info-graphics.
> Refresh BTCPayVsOthers

- docs/Translate.md
> Translation.md updates

- docs/README.md
Continuing on #678 
- Adds new supporter on the front-end
- Re-arranges okcoin
> re-arrange okcoin add nomics

- docs/FAQ/FAQ-LightningNetwork.md
Added a new FAQ and linked a missing faq in the menu
> Add restart c-lightning faq

- docs/FAQ/README.md
> Add how to restart c-lightning to readme

- docs/FAQ/FAQ-LightningNetwork.md
- docs/FAQ/README.md
Provided via the comments in [this issue](https://github.com/btcpayserver/btcpayserver/issues/1845).
> Add LND macaroon info

- docs/WalletSetup.md
> Explain private key derivation from the seed #593

- docs/Contribute/ContributeWrite/WriteBlog.md
Part of #671 
* Creates WriteBlog.md in Write folder
_config.js will be updated once all Write docs are created._
> Contribute Refactoring - Create WriteBlog.md

- docs/Contribute/ContributeWrite/WriteDocs.md
Part of #671 
* Creates WriteDocs.md inside Write folder
_config.js will be updated once all Write docs are created._
> Contribute.md refactoring - Create WriteDocs.md

- docs/.vuepress/config.js
- docs/Contribute/ContributeWrite/README.MD
Part of #671 
* Create Readme.md under ContributeWrite folder
* Update config.js to include #684 #686 #687 #688 under ContributeWrite
> Contribute.md refactoring - ContributeWrite README.md

- docs/FAQ/FAQ-Deployment.md
- docs/FAQ/FAQ-LightningNetwork.md
- docs/FAQ/README.md
> Add existing ln node question to FAQ

- docs/Contribute/ContributeDev/ContributeDevCode.md
- docs/Contribute/ContributeDev/ContributeDevTest.md
Part of #671 
* Adds a table of contents to ContributeDevCode.md and ContributeDevTest.md
* Makes `BTCPayServer` `BTCPay Server` for consistency.
> ContributeDevCode and DevTest table of contents + BTCPay Server for consistency

- docs/HotWallet.md
Add danger warning to hotwallet.md for sharing server credentials with others.
> Hot wallet warning

- docs/Contribute/README.md
- Make it more concise
- Link to ContributeDevTest.md
- Re-phrase to make language more suitable for documentation and easier fot translations in the future.
> Update Contribute Readme.md

- docs/Contribute/ContributeDev/ContributeDevCode.md
- docs/Contribute/ContributeDev/README.md
- docs/FAQ/FAQ-General.md
close #711 
- add [Greenfield Dev Doc](https://github.com/btcpayserver/btcpayserver/blob/master/docs/greenfield-development.md) to contribute docs
- update greenfield faq
> add new greenfield doc to contribute docs

- docs/Contribute/ContributeDev/ContributeDevCode.md
- docs/FAQ/FAQ-General.md
- Organize doc TOC
- Update contribute FAQ question
> formatting and contribute faq

- docs/FAQ/FAQ-LightningNetwork.md
> Update lightning with pruning FAQ

- docs/ThirdPartyHosting.md
> Additional info to thirdparty doc

- docs/Contribute/ContributeDev/ContributeDevTest.md
with #setup-regtest-network-local-btcpay-server
as this  #setup-regtest-network-and-local-btcpay-server  = & creates a broken link
@britttttk
> fixed broken link

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- package.json
- setup-deps.sh
Builds on #751 and integrates the external configurator docs.
Closes #751.
> Integrate configurator docs

- docs/LightningNetwork.md
- updates to the backup info warning (link to noseedbackup FAQ)
- mention pruning in implementation choice (link to ln pruning question in FAQ)
- add eclair, closes #362
> Update lightning doc

- docs/FAQ/FAQ-Deployment.md
- docs/FAQ/README.md
- docs/Troubleshooting.md
- renew ssl to faq
- updates to troubleshooting doc
> Add how to renew SSL to FAQ

- docs/FAQ/FAQ-Synchronization.md
- docs/FAQ/README.md
- docs/README.md
- docs/Troubleshooting.md
- docs/TryItOut.md
Close #770 
- Add how to use bitcoin-cli to get Bitcoin node info to Troubleshooting.md
- Updates to sync FAQ
> Bitcoind sync status

- docs/Contribute/ContributeDev/ContributeDevTest.md
- docs/HotWallet.md
- docs/LedgerWallet.md
- docs/Payjoin.md
- docs/TryItOut.md
- docs/WasabiWallet.md
@pavlenex sorry that PR was not complete see my comment in #773
> Ui updates xpub

- docs/Wallet.md
I believe this is all the possible wallet tx labels
> Add tx labels to wallet doc

- docs/Contribute/ContributeDev/ContributeDevTest.md
> Add more info to contribute dev test

- docs/.vuepress/theme/components/PageEdit.vue
- package-lock.json
- package.json
- setup-deps.sh
Closes #787.
Since we are overriding the edit link template anyways I found a way to do this without a PR in VuePress :)
> Add edit links for external and assembled pages

- docs/Troubleshooting.md
added thunderhub container name for the consistency
> added thunderhub container name

- docs/RPi4.md
- package.json
* Updates the link to new functional one
* Edits one title and a sentence to reflect name change in OS.
> Linkcheck 404 - Update broken link

- docs/FAQ/FAQ-Apps.md
- docs/FAQ/FAQ-Stores.md
- docs/FAQ/README.md
- docs/Invoices.md
Close #741
- Add invoice details section to Invoice.md
- Add buyer information FAQ
> Add how to collect Buyer Information to FAQ 

- docs/FAQ/FAQ-Wallet.md
- docs/FAQ/README.md
- docs/HardwareWalletIntegration.md
Close #810 
- Add Trezor issue FAQ question to Wallet.md
- Add Advanced Settings section to HWI (Vault) doc with Trezor FAQ reference
> Document Trezor signing issue

- .github/FUNDING.yml
This ensures the funding link in shown in this repository :)
> Added missing funding configuration

- docs/FAQ/FAQ-Integrations.md
Once https://github.com/btcpayserver/btcpayserver-doc/pull/816 is merged, the best guide is the one available in this repository.
> Updated integration FAQ for PrestaShop

- docs/Contribute/ContributeDev/README.md
- docs/Contribute/ContributeMisc.md
- docs/Contribute/ContributeWrite/README.md
- docs/Contribute/README.md
- Improve contribute readmes to be more clear
- Additions to writing & dev readmes
- Add Github Discussions to misc contribute doc
> Improve contribute docs

- docs/FAQ/FAQ-Deployment.md
Update bitcoin.custom.yml structure to allow for RPC authentication
> Update bitcoin.custom.yml structure

- docs/ManualDeploymentExtended.md
useradd -m (create home), -s (shell) /dev/null is not valid, must be sudo useradd -M (no home) admin && sudo usermod -L (lock account) admin
> Unprivileged user creation

- docs/FAQ/FAQ-ServerSettings.md
- docs/FAQ/README.md
> Add SSH Maintenance error to FAQ

- docs/.vuepress/config.js
- docs/.vuepress/redirects.js
close #800 
@pavlenex please review with respect to your comments in the original issue.
> Add shopware external link to integrations

- docs/HardwareAsAService.md
- docs/Troubleshooting.md
closes #853
* Adds a disclaimer in HardwareAsAService.md stating that questions, bugs and issues should be directed to providers.
> HardWareAsAService.md support disclaimer

- docs/FAQ/FAQ-General.md
- docs/FAQ/README.md
Closes #846 
Resolves [#2260](https://github.com/btcpayserver/btcpayserver/discussions/2260#discussion-2961595)
* Adds question to General FAQ + question summary
* Adds question in FAQ.md summary
> Add FAQ question - "Charging for using my instance"

- docs/FAQ/FAQ-Wallet.md
> Updates to wallets FAQ

- docs/FAQ/FAQ-Stores.md
- docs/Invoices.md
> Explain archived invoices and link FAQ

- docs/AzureDeployment.md
- docs/HardwareDeployment.md
- docs/LunaNodeWebDeployment.md
- docs/ManualDeployment.md
- docs/TryItOut.md
I changed some of the HTTP links to HTTPS to avoid redirects and improve their loading time.
> Change HTTP to HTTPS links

- docs/GoogleCloudDeployment.md
- package.json
Trying to make [deploy previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) work for the docs …
> Netlify deploy previews

- docs/Support.md
I need to remove my LinkedIn profile..
> Update contact details

- docs/.vuepress/redirects.js
As brought up in #884 and [discussed on Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/7q41nj57djga58awrkx8h6s7he).
> Create redirects for moved wallet pages

- docs/ReverseSSHtunnel.md
A few additions and updates to make it work for me.
> Update reverse SSH guide

- docs/.vuepress/styles/index.styl
As brought up by @Zaxounette on [Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/n9izm3acnidh58byzbokr1w9fa).
> Fix layout overflow

- README.md
- docs/README.md
Merge & squash after [#2536](https://github.com/btcpayserver/btcpayserver/pull/2536)
> Remove supporters

- docs/ReverseProxyToTor.md
Path was pointing to service instead of configuration file.
> Update path of configuration service

- docs/Wallet.md
Inspired by https://github.com/bitcoin/bitcoin/blob/master/doc/psbt.md#psbt-in-general
Gets linked to in btcpayserver/btcpayserver#2559
> Improve PSBT explanation

- package.json
Because of their firewall restrictions the CI cannot access the site (Error 403)
> Exclude PNXBET from linkcheck

- docs/ReverseProxyToTor.md
Solved WebSockets proxy issues.
> Updated mapping and proxy requests

- docs/FAQ/FAQ-LightningNetwork.md
- docs/Troubleshooting.md
> Remove freenode webchat links

- docs/ReverseProxyToTor.md
Adding domain to requirements and on the webserver part as I've found other people asking this.
> Add domain to requirements

- docs/FAQ/FAQ-LightningNetwork.md
- docs/FAQ/README.md
This was brought up multiple times recently ([Mattermost](https://chat.btcpayserver.org/btcpayserver/pl/8864hxom7jrkipu3n6s9d3yowe), btcpayserver/btcpayserver#2651), so I figured it would be good to add it to the docs :)
> LN FAQ: How to edit lnd.conf

- docs/FAQ/FAQ-Stores.md
- docs/FAQ/README.md
> Add sats denomination FAQ entry

- docs/FAQ/FAQ-General.md
- docs/Refund.md
Does this look like it'll resolve #952?
It looks like my IDE removed a bunch of spaces too, I can remove that from the commit if needed.
> Add notes and links about merchant refunds

- .gitignore
- docs/.vuepress/config.js
- package.json
- setup-deps.sh
I've added them to the Features section -- I think it fits there, but I'm open for other suggestions.
> Integrate Vault docs

- docs/FAQ/FAQ-Integrations.md
Will squash the commit, decided to completely remove the link.
> Fix 403 on a linkcheck by removing a link

- docs/FAQ/FAQ-LightningNetwork.md
Hi! Just read the documentation and wanted to correct this.
> Minor semantic correction

- docs/.vuepress/config.js
Adds the docs for recently added Docker plugins.
> Add new docker plugins

- docs/FAQ/LightningNetwork.md
https://github.com/lightningnetwork/lnd/pull/5154
> Remove warning of running LND on pruned node

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- setup-deps.sh
- Added Zapier to the menu
- Added docs + images to the `setup_deps.sh` script so it pulls and updates automatically
> Added Zapier

- docs/Contribute/DevCode.md
- docs/Deployment/ManualDeployment.md
- docs/Deployment/ManualDeploymentExtended.md
- docs/Development/Altcoins.md
- docs/Development/LocalDev.md
> Update install instructions for .NET 6.0

- docs/BTCPayVsOthers.md
- docs/TryItOut.md
- docs/UseCase.md
- docs/Walkthrough.md
Fixed a few minor grammar errors in the documentation.
> Documentation grammar

- docs/Invoices.md
Quick fix since people were confused with the table. 
closes #1046 
In the next issues this page needs to be updated, graphics as well.
> Invoices status table update

- docs/.vuepress/styles/index.styl
> Add border around content images

- docs/.vuepress/public/styles/btcpayserver-variables.css
> Add background color to code elements

- docs/Deployment/AzurePennyPinching.md
- docs/Deployment/ManualDeploymentExtended.md
- docs/Deployment/RPi3.md
- docs/Deployment/RPi4.md
Emoji's might not always show properly and they are used inconsistently. After talks with pavlenex, decided to clean up all the pages and stick to no emoji's
> Took out all emoji in pages.

- docs/Deployment/ManualDeployment.md
- docs/Deployment/ManualDeploymentExtended.md
With NBXplorer changes, the manual deployment doc should be updated.
> Update manual deployment doc

- docs/Shopify.md
Added new video by @webwworthy in docs in addition to #1041
> [Update] Added new Shopify video by Webworthy to docs

- docs/.vuepress/config.js
- setup-deps.sh
We didn't have them in here, though we link to them. I can also link to it in #1103.
> Integrate FastSync docs

- docs/FAQ/LightningNetwork.md
Closes btcpayserver/btcpayserver#3722
> FAQ: How to redirect a Lightning Address

- docs/FAQ/LightningNetwork.md
Yo,
As posted by @petzsch there was a request to add this information on docs.
I felt FAQ would be suiting for it.
closes  #1106
> Update FAQ with Rescan LND

- docs/.vuepress/config.js
- docs/Deployment/DreamlabNetwork.md
Got pointed to a typo and a name convention update :)
> Typo fixes on dreamlab deployment

- docs/Deployment/DreamlabNetwork.md
Yo,
just Added DreamLab intro video.
Made by @Webwworthy!
> Added DreamLab intro video

- docs/FAQ/Wallet.md
Yo,
Saw @britttttk her issue documenting this into the FAQ.
closes #960
> FAQ update Address rotation

- docs/Deployment/README.md
Yo yo,
Got pointed to this list by Dream Lab, they where missing so was Voltage cloud.
> Added Voltage and Dreamlab to list deployments

- docs/WooCommerce.md
This adds a "success" response to docs for others to see that a 500 response is OK and the request is not being blocked with a 403.
> Update WooCommerce Troubleshooting

- docs/Accounting.md
Thanks @pavlenex for the video on how to contribute!
> Add fields & correct typo in Accounting

- docs/VirtueMart.md
Updated virtuemart.md for YT content
> Updated virtuemart.md for YT content

- .gitignore
- docs/.vuepress/config.js
- setup-deps.sh
Added as a separate Plugins section in the User Guide, so that we can host more plugin docs there.
> Add LNbank docs

- docs/Wallet.md
Yoo yoo
Looked at this #950  one and found small things only. Also deleted a double entry for PSBT at the bottom where it's talked through in a section higher up. 
Maybe point should look at more of the Wallet page then just this.
> Slightly updated Wallet.md

- docs/Contribute/Write.md
- docs/CreateWallet.md
- docs/CustomIntegration.md
- docs/Development/TestnetDemo.md
- docs/Payouts.md
- docs/Shopify.md
- docs/WooCommerce.md
Yoooo
just some small updates on proper titles on pages create wallet and testnet demo.
> Small updates on proper titles

- docs/README.md
Yo yo
This is for #994 :) 
cc @pavlenex =D
> First updates to explore by topic

- .gitignore
- docs/.vuepress/config.js
- setup-deps.sh
Will extend them as the plugin develops.
> Add PodServer docs

- docs/.vuepress/config.js
- setup-deps.sh
Adds detailed import instructions for compatible wallets as a subpage.
> LNbank: Add LNDhub Compatibility docs

- docs/FAQ/General.md
Yooo
Looked at the open issue of bk #852 once more. 
Added the part of the discussion in https://github.com/btcpayserver/btcpayserver/discussions/2282 to FAQ 
Maybe needs better title ? otherwise i think this closes it and moves on in #1142  
closes #852
> Update on FAQ with webhook bitpay Questions

- package-lock.json
- package.json
- setup-deps.sh
Reveals problems as reported in btcpayserver/btcpayserver#4231.
> Swagger: Deep-merge and validate OpenAPI files

- README.md
- docs/.vuepress/includes/supporters.html
See btcpayserver/btcpayserver#4265.
> Remove Nomics as BTCPay Supporter

- docs/Apps.md
Updated the "Payment Button" instructions.
> Apps.md_PaymentButtonUpdates

- docs/FAQ/Stores.md
Yo yo
Added a short topic on RBF flagged tx in a 0conf configured store setting.
closes #1197
> Updated stores FAQ with RBF/0conf topic

- docs/FAQ/Wallet.md
Yo.
Just added short FAQ on " Does BTCPay Server use mempoolfullrbf=1 "
> Update WalletFAQ with mempoolfullrbf=1

- docs/UseCase.md
I manually proofread and ran content through Grammarly.
> Update UseCase.md to fix typos and grammar

- docs/HardwareWalletIntegration.md
Yo
Update video to new BTCPay Vault HWW video
> Update video to new BTCPay Vault HWW video

- docs/WooCommerce.md
Yo yo
as mentioned in #1233 replaced deadlink with webarchive link.
closes #1233
> Update dead link woocommerce

- docs/HardwareWalletIntegration.md
Yo
was notified that links on YT are broken. This was the last one changed. This PR is in attempt to fix this.
> Docs has broken YT videos.

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- setup-deps.sh
I will release the plugin together with the next BTCPay Server version.
> Add LNDhub API plugin docs

- docs/FAQ/Deployment.md
Fixes btcpayserver/btcpayserver#4836 — see comments there.
> Improve Let's Encrypt location directive

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- setup-deps.sh
Mr. Kukks went through the effort to create documentation for his plugins, we should display them more prominently.
> Add kukks' plugins

- docs/FAQ/Deployment.md
> FAQ: Update uninstall entry with teardown script

- package-lock.json
- package.json
- setup-deps.sh
> Remove the now-deprecated swagger-cli

- docs/Apps.md
Amended the Payment Button section to point React devs to the newly available React package. Any suggestions or corrections welcome.
> Add instructions for React Pay Button package to Apps.md

- docs/AdvancedForms.md
- docs/Forms.md
Context: btcpayserver/btcpayserver#5463
> v1.12: Add amount multiplier example

- README.md
- docs/.vuepress/includes/supporters.html
Part of btcpayserver/btcpayserver#5684
> Remove ESC as a supporter

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- setup-deps.sh
Tackles https://github.com/btcpayserver/btcpayserver-doc/issues/1372
Dependent on the following PRs:
- https://github.com/btcpayserver/grandnode/pull/5
- https://github.com/btcpayserver/nopcommerce/pull/9
> Add Grandnode and nopcommerce to docs

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- setup-deps.sh
> Add xenforo to btcpay docs

- docs/Deployment/GoogleCloud.md
- docs/Deployment/HardwareAsAService.md
- docs/Development/Plugins.md
- docs/Walkthrough.md
> chore: fix typos

- docs/Deployment/webdeployment.md
Hey there,
I have added Elestio as a deployment method as it provides a fully managed service for the BTCPay Server.
> feat: Elestio added as deployment methods

- docs/LightningNetwork.md
Resolves #1296   by including Alby to BTCPay docs
> include alby extension

- docs/Deployment/LunaNode.md
> Remove link

- docs/.vuepress/config.js
- setup-deps.sh
@ndeet  included plugins documentations for some other plugins as external links in the plugin navs
> Include plugins in nav as external

- docs/Development/GreenFieldExample-NodeJS.md
The first edit was to fix Buffer.from being called again, Buffer.from does not accept a string argument and outputs bytes. The current code had the following flow: 
x = Buffer.from(digest<string>)
y = Buffer.from(x<bytes>) -> Error, expecting str
It was simple to just remove y as it's redundant. 
The second edit was to allow for those using TypeScript to overcome the simple errors they will run into.
> correct redundant buffer call causing error, add typescript workaround

- docs/.vuepress/config.js
- setup-deps.sh
Integrate wix documentation to BTCPay docs.
Dependent on: https://github.com/btcpayserver/wix/pull/1
Cc. @pavlenex
> documentation for wix integration

- .gitignore
- docs/.vuepress/config.js
- docs/.vuepress/preprocessMarkdown.js
- setup-deps.sh
Resolves #1443 
Here @dennisreimann, kindly review
> fix edit links.. update Wix docs directory

- docs/Deployment/HardwareAsAService.md
> add BitcoinPayBox to the list of HOS

- docs/Deployment/LunaNode.md
> Adding BTC Sessions video to docs.

- docs/.vuepress/config.js
- setup-deps.sh
> shopify v2 docs

- scripts/btcpayserver-rpi4-install.sh
avoids needless interruption for the user
> add -y to apt update

- docs/Deployment/LightningInABox.md
> Remove scam/gambling link.

- docs/ShopifyV2.md
More Shopify FAQ based on user feedback
> include more faq

- docs/FAQ/Deployment.md
Thank you @Retropex for the initiative on this topic. 🔥
> add Knots to deployment FAQ

- docs/FAQ/LightningNetwork.md
- docs/Walkthrough.md
remove redundant words in comment
> chore: remove redundant words in comment

- docs/Support.md
> change mattermost link from freelance-jobs to dev

- docs/FAQ/README.md
correct missing Readme.md/Index of new FAQ question.
> add Knots to FAQ/Readme.md
