btcpayserver/btcpayserver-doc

README.md

make it more explicitly clear that we support both PostgreSQL and SQLite

Make it clearer that it supports two different DBs

---

FAQ.md

I suggested in an [issue on btcpayserver-docker](https://github.com/btcpayserver/btcpayserver-docker/issues/34) that we find a way to use an already synced blockchain with BTCPay when possible.
The point is to allow people that already run a node to avoid a long and costly resync and leverage the work already done for their BTCPay full node.
I made a few modifications to `docker-compose.generated.yml`, and made BTCPay mount my existing `.bitcoin` directory instead of the docker volume `bitcoin_datadir`.
It doesn't seem to represent any risk, I was able to reuse the same directory with plain `bitcoind` thereafter, and then again with BTCPay without issue.
I propose this very easy "how to" as an addition to the FAQ, waiting maybe for a more durable solution one day.

[docs] Add how to use existing bitcoin data_dir for the btcpay docker

---

Support.md

I propose to modify the Support.md page as such as a quick fix for the issue with the Slack being used as a channel for support.
I found out that on Github's Support.md file, the NBitStack is mentionned only at the bottom, with the Slack, making it look like there are two equal alternatives for looking for support while they really aren't.
A lot of people are showing up on the Slack to get help, but it does not suit our need well : 
* Because of the message limit, it becomes harder and harder to find an issue that as already been answered a few days ago
* Searching for a specific info is a mess anyway !
NBitStack is much more suited for that, and already concentrate a great deal of issues and info that most users could browse themselves before getting to the Slack.

[doc] update Support.md

---

README.md

Fixing Magento > Magneto typo in README.md.

---

FAQ.md

This PR adds a section to FAQ about setting up the gap limit in software wallet to avoid confusion merchants may have and the panic of "missing funds" from their software wallets.

Add Gap_Limit to FAQ.md

---

Translate.md

Adding Translation document: Ref #49
PR allows us to:
* Tell users how to translate BTCPay
* Have an instruction link on Transifex

Adding Translation.md

---

Translate.md

Fix country code instruction.
Move {{}} into a code block for GitBooks.

Typo and fix format

---

ManualDeploymentExtended.md

This PR adds some little things
- instructions for creating the `admin` user referenced throughout
- clarifying comments in the nginx config
- extends example BTCPay Server config
- clears some trailing whitespace

Minor improvements to the extended manual instructions

---

Theme.md

Increase the blockstream css example background invoice - area behind the QR code. Fixes failed scanning.
Fix for issue  285 "Blockstream dark theme causes QR code scanning failure"

Update blockstream css example

---

Magento.md

The current doc page for Magento was outdated and did not contain any useful info really.
Now mentioning Magento versions 1 and 2 and removed useless links.

Updated Magento docs

---

ConnectWallet.md

After #308 is merged, this PR can be reviewed. This PR provides a ConnectWallet.md page which lists recommended wallets to use with BTCPay and links to in-depth step by step tutorial for each wallet.
After this PR is merged, we only need to tackle Summary.md to structure all the new pages before we finally close #252

Add ConnectWallet.md

---

LocalDevelopment.md

Mostly shuffled thinsg around a bit and extended the resources with more links.
Also emphasizing that the dockerized setup from the tests directory is the recommended option.
Closes #174.

Improve developers documentation

---

Translate.md
TryItOut.md
UseCase.md

Closes #330 
And on top of that removes demo button links, until we have a new demo button page on which @vswee is working on. I've added a comment for this one in #

Replace store link, remove button demo

---

RPi3.md
RPi4.md

Set BTCPAY_ENABLE_SSH=true in Raspberry Pi deployment guides

---

RPi3.md
RPi4.md

Otherwise the [maintenance features](https://docs.btcpayserver.org/faq-and-common-issues/faq-serversettings#maintenance-1) do not work, as the firewall blocks SSH connections from the Docker container.

Allow ssh connections from docker network on RPI

---

ThirdPartyHosting.md

LAWGATE.io has successfully set up a self-hosted BTCpayserver instance with working email for password recovery. At this point we would like to open it for people who don't want to go thru the hassle of running their own instance.

Add a new BTCPay third-party host

---

README.md

The image in the preview won't be visible until #1119 in the main repository is merged.
Will look exactly as in the #1119
**Please don't merge until #1119 is merged.**

Add Supporters section to docs readme file

---

FAQ/FAQ-Synchronization.md

#372 
Not sure if we need to mention the error: `Prune: last wallet synchronisation goes beyond pruned data.`

Update FastSync FAQ

---

ElectrumWallet.md

Electrum Wallet doc overhaul with BTCPay / ElectrumX integration docs - take 2 after the repo "deletion" stuff
This is the second version of https://github.com/btcpayserver/btcpayserver-doc/pull/367 as requested by @pavlenex 
(the first version should be deleted)

Electrum Wallet doc overhaul w BTCPay / ElectrumX integration docs-2

---

RPi4.md

make the RAM filesystem for logs command an actual command that you copy paste instead of leaving noobs to figure it out

RPI4: RAM filesystem for logs  command fix

---

RPi4.md

Most of the tutorial is done as root, so the superfluous `sudo` prefix can be omitted. As the repo is also cloned as root, `cd ~pi/btcpayserver-docker` was not correct.

Improve Raspberry Pi 4 docs

---

ReverseSSHtunnel.md

Adding the copy of the page from my tutorials which came to be when I was setting up a self-hosted BTCpay on my hack0: https://github.com/openoms/bitcoin-tutorials/blob/master/ssh_tunnel.md
The setup is running non-stop since weeks now without issues.
Any advice to modify, update and link in specific places is welcome.

add how to forward ports with a reverse SSH tunnel

---

RPi4.md

- the old temperature command (`sudo -svcgencmd measure_temp`) does not work on Rasbian 10 (Buster) 
-  add a while loop to take multiple measurements every 1 second
- fix `ufw` firewall, the old command on  Rasbian 10 (Buster)  would produce "ERROR: Couldn't determine iptables version" (see https://raspberrypi.stackexchange.com/questions/100598/ufw-and-iptables-on-buster )

Fix temperature command and firewall errors

---

RPi3.md

Using the pi 4 guide, I was setting up my raspberry pi 4 with FastSync and didn't realize I was missing something from the pi 3 guide about how to enable pruning on my node.
This fork adds a comment to the pi 3 guide about why a certain fragment is necessary for FastSync and has a link to more pruning options.

Updating docs to be explicit about pruning with FastSync

---

FAQ/FAQ-Deployment.md

See workaround here
https://github.com/btcpayserver/btcpayserver-docker/issues/263#issuecomment-581472247
The "set -u; echo "$BTCPAY_HOST" makes sure the variable is set. If not, it will print
> -bash: BTCPAY_HOST: unbound variable
and exit early.

Document the workaround for issue with 503 error

---

WasabiWallet.md

The instruction were wrong. 
1. We were modifying the wasabi backend instead of the P2P endpoint.
2. It can now be done without touching the configuration file.
Reported by @AryanJ-NYC

Fix documentation for using your node as P2P source of wasabi (Fix #287)

---

ManualDeployment.md
ManualDeploymentExtended.md

- Update bitcoin core version to 19.1
- Verify sig from https://bitcoincore.org/bin/bitcoin-core-0.19.1/SHA256SUMS.asc
- Update Ubuntu version
- Update .net core download link for Ubuntu 18.04

Update bitcoin core version

---

WasabiWallet.md

some typos and making it more beautiful. Mainly, clarifying that the recovery words alone CANNOT spend the bitcoin - it also needs the password.

Minor fixes

---

Payjoin-spec.md

these links were broken, probably in a re-write that changed headers. I think the new links all work now.

fix broken internal links

---

docs/.vuepress/preprocessMarkdown.js

The regular expression was missing the global flag, so that only the first video preview got replaced. Closes #525.

Fix video integration

---

docs/README.md

- Adds Brit's video that covers features, under the features section.
Don't get confused by the video preview being smaller on GitHub. On VuePress front-end looks good. As the matter a fact, I think this shows we can from now on use 
`https://img.youtube.com/vi/VIDEOURL/mqdefault.jpg` to embed videos and save space for thumbnail upload. Related to #519

Add Features Overview video to readme

---

docs/FAQ/FAQ-Deployment.md
docs/FAQ/FAQ-General.md
docs/FAQ/FAQ-LightningNetwork.md
docs/FAQ/README.md
docs/TryItOut.md

The slugs are generated a bit differently with VuePress' Markdown parser than before, hence some of the permalinks broke.
Fixes #536.

Anchor link fixes

---

docs/Troubleshooting.md

I propose to change the suggestion to get a log output, from:
`docker logs --tail 40`
to
`docker logs --tail 100` 
The reason is simple. As a newbie (as i am) you probably just copy and paste, and with `--tail 40` there is a non negligible chance that you miss the key information. This happened to me.

docker logs --tail 100 instead of --tail 40

---

docs/.vuepress/enhanceApp.js
docs/.vuepress/preprocessMarkdown.js
docs/.vuepress/styles/index.styl

@britttttk mentioned on the chat, that she isn't able to play the videos on an iOS 7 device. Could reproduce it with an older iPad. Here's the fix and also a proper fallback for disabled JavaScript.

Fix video integration for older iOS

---

docs/.vuepress/redirects.js

Addresses btcpayserver/btcpayserver.org#121, but should be properly fixed with updating the link in the website footer. Nevertheless let's add this redirect as the URL seems to be out there :)

Add redirect for old link

---

.github/workflows/nodejs.yml
docs/.vuepress/__snapshots__/preprocessMarkdown.spec.js.snap
docs/.vuepress/config.js
docs/.vuepress/preprocessMarkdown.js
docs/.vuepress/preprocessMarkdown.spec.js
jest.config.js
package-lock.json
package.json
setup-deps.sh

This moves the rewrite logic for links in external repo docs to JavaScript, where we have more control and context than in the bash script. 
This fixes #566 and adds tests for the replacements done in `preprocessMarkdown`, so that we can ensure the desired output.
To test this locally, please run `npm install && ./setup-deps.sh` after checking out this PR.

Improve external repo links

---

.editorconfig

This is a widely used file that instructs editors about which settings to use. Won't help in every case but it is a baseline.

Add editorconfig for code conventions

---

.gitignore
docs/.vuepress/config.js
docs/.vuepress/public/API/Greenfield/v1/index.html
setup-deps.sh

Pretty straight forward: Checks out the BTCPay Server repo and combines the individual swagger JSON files into one. Copies this to a directory we make available separately from the rest of the docs, as this uses the ReDoc layout.
The link in the sidebar has to be an absolute URL as I haven't found a way to link to an "internal" page as an external resource … so keep in mind you have to manually visit [http://localhost:8080/API/Greenfield/v1/](http://localhost:8080/API/Greenfield/v1/) to see the result.
And you need to run `./setup-deps.sh` after checking out this branch, as the BTCPayServer repo is a new dependency.
Closes btcpayserver/btcpayserver#1613.

Add Greenfield API docs

---

.github/workflows/nodejs.yml
README.md

My recent PR #580 broke the build as the `setup-deps.sh` script now needs to run after the node dependencies are installed.

Reorder build steps

---

setup-deps.sh

Checkout latest release tag, so that we do not publish docs for unreleased APIs yet.

Use btcpay docs for latest release instead of master

---

docs/.vuepress/enhanceApp.js

This fixes #614, which seems to be caused by vuejs/vuepress#2428.

Fix anchor scroll positions on page load

---

docs/ManualDeploymentExtended.md

Ran the command on Ubuntu server 20 running on a raspberry pi 4 and got the following:
```
$ netstat -tlnp | grep tor
(Not all processes could be identified, non-owned process info
will not be shown, you would have to be root to see it all.)
```

Command to check tor needs to be sudoed

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/PageEdit.vue
docs/.vuepress/theme/index.js

Closes #596. Adds the "Didn't find an answer?" link as proposed. 
This link prepopulates the issue form as displayed below. (Title and Body are prepopulated, Question label pre-assigned)

Add "Didn't find an answer?" link to page footer

---

docs/ManualDeploymentExtended.md

Updated extended manual deployment instructions for Ubuntu 20.04 and latest versions of application components (btc, lnd and rtl).
Adjusted steps where necessary for changes to deployment instructions for each application.
Changed the Bitcoin Core instructions to build from source rather than download. WIth this change the instructions now document a full build from source solution for BTCPay Server.

Updated extended manual deployment instructions for Ubuntu 20.04

---

docs/LocalDevelopment.md

With the recent refactor of isolating altcoins, development doc needed to be updated: ping @xpayserver

Add documentation on development environment setup

---

docs/.vuepress/config.js

Finally vuejs/vuepress#2408 got merged and is availabe as a release, so now we can hide the single "ColdCard Wallet" item initially. This is to prevent the assumption, that only ColdCard is supported.
Before:
After:

Hide single "ColdCard Wallet" item initially

---

docs/BTCPayVsOthers.md
docs/Invoices.md

Kukks mentioned in a recent tweet the invoice translator that is built in BTCPay Server.
It made me realize I couldn't recall if I saw mention of it in the docs, and searching in them resulted in nothing.
* Adds a § mentioning invoice translating in `invoice.md`
Unsure if I should add a screenshot. Doesn't seem absolutely necessary as usage is straightforward.

Add Invoice translation § to btcpayvsothers.md

---

docs/FAQ/FAQ-LightningNetwork.md
docs/FAQ/FAQ-Synchronization.md
docs/FAQ/README.md

closes #718
- add how to disable pruning to faq
- add how to enable pruning to faq (already in docker-repo faq but gives a more clear example in docs-repo for sync issue reference
- remove prune instructions from random places
- reorder sync issues based on how common they are in chats (afaik)
- add accidental removal of pruning to list of why node is syncing

Add disable pruning to faq

---

setup-deps.sh

Refines the lookup for the latest release tag for btcpayserver , so that only API docs for released versions get published.
The previous version incorporated all tags, assuming there are only release tags, which isn't the case.
This change ensures the tag name starts with `v[0-9].`

Fix latest tag lookup for btcpayserver repo

---

docs/Apps.md

Adds Light POS section under Point of Sale in apps.md
Closes #735
Specifically
* Adds a paragraphe mentionning the three possible views for a POS app
* Adds some `code` formatting for easier reading
* Adds a link to the blog post relating to the new Light POS feature.
Be advised, I updated said blog post to include a custom anchor to link directly to the relevant paragraphe `Simple Point Of Sale`.
Said link can be deleted in the future when we feel that most users will have updated to that version.

Add Light POS section under Point of Sale in apps.md

---

docs/FAQ/FAQ-Deployment.md

A few of the relative links where broken in `FAQ-Deployment`.
Some of them because of typos (ie summary question not matching the text question) and for others because of `FAQ-Deployment.md` term in front, for some reason).
This PR fixes the `broken links` but also:
* Deletes `FAQ-Deployment` in the markdown summary relative links, cleaning them up for visibility
* Reorders summary questions to comply with the actual order of the questions in the text
* Renames `Cause N` to `Cause 5` and creates corresponding summary question/title & link

FAQ-Deployment - Broken links fix + Link cleanup

---

docs/Deployment.md
docs/ManualDeployment.md
docs/ManualDeploymentExtended.md
docs/Troubleshooting.md

Relates to #769 .
Adresses the initial issue, but not the suggestion in https://github.com/btcpayserver/btcpayserver-doc/issues/769#issuecomment-727656623 
* Convert an existing sentence into a warning in `Deployment.md`
* Add a short bold indication in the options bullet-points in `Deployment.md`
* Copy warning from `ExtendedManualDeployment.md` into `ManualDeployment.md`, just under the first H1
* Include an additional sentence to be explicit the community will not provide extensive support/support time for this deployment
* Add this additional sentence to already existing warning in `ManualDeploymentExtended.md`
* Add warning in `Troubleshooting.md` in the "Ask for help" section.

Manual deployment warnings

---

docs/.vuepress/config.js
docs/.vuepress/styles/index.styl

Here we go with another stab at #628. 
- Better results display (no more subcategory column)
- Decrease typo tolerance to have more focused results
- Remove `hitsPerPage` param, which filled up the results to at least ten
The last point reduces the search results to a maximum of five items, which is not exhaustive for terms like "wallet", as you can see in the examples below. However, I find this to bring more focus to the relevant results – the idea would be that people provide more context in case the initial five results aren't what they expected. But yeah, ideally there'd be a way to have a mix of Algolia returning all results that fit a term and not fill up results with unnecessary garbage, just because one demanded a certain count of results per page.
In general the index update …

Search improvements

---

docs/BTCPayVsOthers.md

Since the translator is obsolete/depreciated and the official mainnet `/translate` link is a 404 it can be deleted from the docs.
I simply added a hint saying it's depreciated starting v1.0.6.3.
I left the paragraphe above the link because not all users will update right now. Can delete it in a few months ?
Thoughts ?

Delete link to official mainnet translator

---

docs/FAQ/FAQ-Apps.md
docs/FAQ/FAQ-Wallet.md
docs/LedgerWallet.md
docs/ThirdPartyHosting.md
docs/WalletSetup.md

Closes #805 
* af12968, 788b59e and bd185c6 simply replaces `Xpub` by `extended public key` in different files where feasible. 
Excludes image and link titles or adresses.
* c7a1551 Adds a `tip` in `WalletSetup.md` briefly explaining that BTCPay converts Ypub and Zpub to Xpub without incidence feature-wise.
* 741e1dc Adds another `tip` in `FAQ-Wallet.md`
* 182a1ab Replaces `Xpub` by `extended public key` where relevant
I kept this simple, as to not overwhelm users that could be uneducated to the specifics of these formats. 
It may be too simple.
Thoughts ?

Ypub-Zpub to Xpub conversion

---

docs/RPi4.md

Fixes some of the code snippets from the RPI4 docs.
- Sudo was used when configuring iptables and rebooting but the user was supposed to be root already
- `ufw status` cannot be queried before enabling it, so swapped the order of the commands. This may be troublesome since if the ssh rule was not properly configured and the user was setting this up via ssh, the connection can be terminated forcing the user to connect physically.
- Added a snipped telling the user to switch back to root after rebooting, since all the `ufw` commands are supposed to be run as root.

Some fixes in RPI4 docs

---

docs/.vuepress/config.js
setup-deps.sh

Removes our moneypatch for Vuepress now that there is a release with vuejs/vuepress#2674 merged.
If the linkcheck works for the internal pages then this is good to go.

Remove Vuepress moneypatch

---

docs/Altcoins.md

* Deletes the Altcoin list in Altcoin.md.
This list is a duplicate with the one stated in FAQ-Altcoin.md, and has no deployment tutorial links.
* Adds wording to indicate the existence of such a list in FAQ-Altcoin.md

Delete Altcoin list in Altcoin.md

---

docs/README.md
docs/RegisterAccount.md
docs/ThirdPartyHosting.md

Hopefully closes #812 and closes #840 
* Adds wording redirecting viewers to appropriate sections. Mainly the demo official demo instance, third party hoster list (directory) or deployment page.
* Add rewording and addition in an attempt to make more clear the fact that BTCPay is not a company.
* Add `tip` mark to make directory third party hoster list more visually seen..

Register btcpay rewording

---

docs/ManualDeployment.md

I recently had to do a minimal setup of BTCPayServer in testnet mode and it took me a while to find the testnet commands to do it so I thought these additions to the docs might be helpful.

update manual deployment with testnet commands

---

docs/FAQ/FAQ-General.md
docs/FAQ/README.md

Close #156 
Since it's documented in btcpayserver-docker repo, I've added an FAQ to direct to users to that. I don't think we need more documentation for this.

Add backups to general FAQ

---

docs/ManualDeploymentExtended.md

Line 944 - symbolic link creation fixed - ln -s /etc/bitcoin/bitcoin.conf ~/.bitcoin/bitcoin.conf should be ln -s ~/.bitcoin/bitcoin.conf /etc/bitcoin/bitcoin.conf

Update Manual Deployment

---

docs/HardwareAsAService.md

LuxNode doesn't seem to be available (anymore?), the URL does not respond and I couldn't find any information on that service online.

Hardware As A Service: Add Umbrel, remove LuxNode

---

docs/.vuepress/config.js
docs/ReverseProxyToTor.md

This is an alternative for the Reverse SSH Tunnel setup. It requires no port forwarding on the LAN and also hides the IP of the host.

Add reverse proxy to Tor setup

---

README.md
docs/README.md

- Adds a new supporter logo to the readme of docs.
- Depends on https://github.com/btcpayserver/btcpayserver/pull/2389

Add new supporter to readme

---

docs/FAQ/FAQ-Integrations.md

In #822 I committed a tip, but forgot to close it using the `: : :` tags.
This resolves that issue + a typo.

FAQ/Integrations.md - Fix tip closing missing + typo

---

docs/ReverseProxyToTor.md

Note: The `Content-Security-Policy` HTTP header has a frame-ancestors directive which obsoletes the `X-Frame-Options` header for supporting browsers.
I've found that if I create a payment button and run it on a different domain, the modal will not run because of this option. With the `X-Frame-Options` you can't indicate more than one domain but you can with the `Content-Security-Policy`. For example you can use:
```
add_header Content-Security-Policy "frame-ancestors 'self' *.domain.com otherdomain.com;";
```
For more information see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Deprecated X-Frame-Options by MDN

---

docs/.vuepress/config.js

related to the vuepress issue with the mobile layout removing viewport meta tags on firefox for Android.
Fix is to explicity define it.
https://github.com/vuejs/vuepress/issues/2369

Fix for mobile layout on firefox

---

docs/Deployment/ReverseProxyToTor.md

Fix “ssl” Directive Is Deprecated, Use “listen … ssl”
The deprecation warning tells you to reconfigure your SSL settings. In nginx 1.10 (and below) you configured SSL using the ssl on;
This setting changed in nginx 1.12 (and above). You now need to configure SSL in the same line as the listen statement. 
Simple fix. Remove the "ssl on" completely
Thanks for the otherwise great tutorial, everything worked out fine after this simple fix!

Fix “ssl” Directive Is Deprecated

---

docs/WooCommerce.md

@NicolasDorier I saw you removed the old video [here](https://github.com/btcpayserver/btcpayserver-doc/commit/d4eecd82a811500407770ab97e5dd8fd3fd64a5f) but I just forgot to update the link to the new video. Somebody is also working on improving my video so there will be a better one in the next few days and I will reopen the PR.

Adding link to BTCPay for WooCommerce V2 video.

---

docs/FAQ/Altcoin.md

This replaces the outdated notes for Monero usage with an up-to-date guide on the process of accepting Monero via BTCPay Server from start to finish:
https://sethforprivacy.com/guides/accepting-monero-via-btcpay-server/

Replace outdated Monero notes on altcoin FAQ

---

docs/Contribute/DevCode.md

guides.github.com moved to docs.github.com and despite having a 301 redirect it fails on linkcheck on all open PRs.

Fix moved url github guides

---

.github/workflows/build.yml

The linkcheck fails quite often due to temporarily unavailable pages. To avoid doing a commit to re-trigger the check and build it might be good to be able to manually trigger a build via the UI, seems this trigger can do just that. See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
Feel free to close the PR if you do not think this is useful.

Add workflow_dispatch trigger to allow manual builds.

---

docs/WooCommerce.md

Added on troubleshooting for checking first if the Webhooks is created on the BTCPay Server under store settings.
On my case it was failing and no Webhooks was created.

Update WooCommerce Troubleshooting / Webhooks

---

docs/Deployment/HardwareAsAService.md

This updates the Umbrel link to their latest website.
Also, a warning should be added for Umbrel. A lot of people are running a shop on Umbrel without realizing Umbrel prohibts commercial use of their software. Using an Umbrel node to sell anything is commercial use.

Update Hardware as a Service page

---

.gitignore
docs/.vuepress/config.js
docs/Deployment/Hardware.md
docs/Deployment/LightningInABox.md

Ping @Bangalisch, @danielcharrua, @dennisreimann 
This is a follow up of https://github.com/btcpayserver/btcpayserver-doc/pull/1148 .
1. I have moved the documentation of cloudflare to the hardware category, as there is no real advantage to use it elsewhere.
2. I renamed the sections concerning solutions to expose your server on internet
3. Changed `Hardware.md` so it isn't an introduction of a specific hardware deployment, and instead an introduction to the three solutions we are documenting.

Re-arrange the hardware documentation

---

docs/FAQ/Deployment.md

Added missing export clauses and reference to created bitcoin.custom fragment, so it is loaded

Fix doc for running existing Bitcoin node

---

docs/.vuepress/config.js
setup-deps.sh

Found them and saw that they weren't part of the docs website.

Add Greenfield auth and development docs

---

docs/Contribute/Agenda.md

Updating the obsolete GitHub links following the transition to Google calendar. 
Change overview:
- updated the links under “BTCPay Server Open Community Calls calendar”
- removed the “Upcoming calls” section since the links were no longer valid
Note: This is addressing issue https://github.com/btcpayserver/btcpayserver-doc/issues/1184

Updated "Contribute" page

---

docs/.vuepress/config.js
docs/.vuepress/redirects.js
docs/Shopware.md

Removed the direct link to the external Shopware 5 plugin as there is now a new Shopware 6 plugin done by coincharge.io. I created a new page and linked both. See also the discussion on mattermost [here](https://chat.btcpayserver.org/btcpayserver/pl/8duuxx187bny9mx9tpyspdtjpy)

Shopware integration page

---

docs/Deployment/ManualDeploymentExtended.md

Changes the instructions to checkout the latest tag instead of pulling from master.
Brought up in btcpayserver/btcpayserver#4544.

Manual deployment: Upgrade to latest tag

---

docs/LightningNetwork.md

Strange wording is found in different parts of the docs, want to start cleaning it up.

Fix grammer in lightning network documentation

---

docs/Magento.md

see broken (not rendered link): https://docs.btcpayserver.org/Magento/

Fix link, url only does not render link on docs page.

---

docs/LightningNetwork.md

Added the location to the hsm_secret for CLN backups. The guide linked points to the default location for the $LIGHTNINGDIR. The location on btcpayserver can be difficult to locate if you are not familiar with docker setups.

Add CLN hsm_secret location

---

docs/PrestaShop.md

Since the PrestaShop plugin has been updated to [version 6.0.0](https://github.com/btcpayserver/prestashop-plugin/releases/tag/v6.0.0), it is time to update the documentation as well.

Update PrestaShop.md to v6.x

---

docs/FAQ/LightningNetwork.md

Can be merged once btcpayserver/btcpayserver-docker#833 gets merged.

LND Watchtower docs

---

.gitignore
docs/.vuepress/public/API/Greenfield/Plugins/index.html
setup-deps.sh
swagger/btcpay.json
swagger/plugins.json

Closes #1343. Once this and btcpayserver/btcpayserver#5400 are merged, we can point to the new plugin docs page via the `externalDocs` field of the [General API Info](https://swagger.io/docs/specification/api-general-info/).

API: Separate core and plugin docs

---

docs/FAQ/LightningNetwork.md
docs/FAQ/README.md

Closes btcpayserver/btcpayserver#5774.

Add "How to edit .lightning/config"

---

docs/Shopware.md

Shopware delisted the plugin in their marketplace because they wanted to charge a 2000,- EUR fee per year even it is an open source and free of charge extension. Crazy.

Remove Shopware marketplace listing for now.

---

docs/Development/GreenFieldExample-NodeJS.md
docs/Development/GreenFieldExample.md
docs/Development/GreenfieldExample-PHP.md

The idea is outlined in issue #1371 where we structure examples for eCommerce use case and also on managing BTCPay Server by creating users and stores. All the examples for PHP, Node.js and cURL have the same structure while differing in details according to language, e.g. you can't really do a webhook validation endpoint with cURL.
Fixes #1371

Restructure API examples, add more

---

docs/Contribute/DevTest.md

Turns out we already have steps on using Docker Hub. I added the steps for doing it with a local build above that Docker Hub section. I did not change the headline of the DockerHub part although it is not ideal but to avoid breaking links.
Also I kept style of that page by camelCasing headlines and adding Steps: to it.
cc @dennisreimann

Adding tutorial how to use a local docker built for testing.

---

docs/.vuepress/config.js
docs/Conference-PoS-guide.md

To access this page in preview you need to manually enter the path `/Conference-PoS-guide/` as there is no menu item assigned yet (as it is unclear where to put it, see below).
**to be discussed:**
- where should we place this guide? A new "Guides" or "How to" section in the User guide? Somewhere else? 
- I left some // todo: where we need to clarify double check
- instead of repeating everything in the guide we should link to existing guides like we do with the Blink plugin setup; we could also link to the [Boldcard plugin readme](https://github.com/NicolasDorier/boltcards-plugin/blob/master/README.md) of Nicolas but it seems this part may be clearer this way if we repeat it with the store names and examples
**todo:** 
- will add some images where relevant, adding it for each tiny step …

Conference PoS and Bolt Card guide.

---

docs/OpenCart.md

Part implementation of #1352 for Open cart.

open cart doc improvement

---

docs/WhatsNext.md

Remove Connecting Additional BTCPay Services

---

docs/Deployment/ManualDeploymentExtended.md

A user got confused about the lack of chart.
Given that migrations now shouldn't happen, I removed a paragraph and clarified the configuration file's settings of BTCPay Server.
[Another PR](https://github.com/btcpayserver/btcpayserver/pull/6507) improve BTCPay's instructions and update the doc link.
See https://github.com/dgarage/NBXplorer/issues/500

Clarify NBXplorer connection string settings

---

docs/Deployment/ManualDeploymentExtended.md

Update documentation to use fullchain.pem for the `ssl_certificate` option. See https://github.com/btcpayserver/btcpayserver/issues/6532 for details.

Use fullchain.pem in ManualDeploymentExtended.md

---

docs/.vuepress/config.js
docs/.vuepress/redirects.js
docs/ShopifyV2.md

- Remove old shopify link
- Redirect old shopify link to shopify v2 link
- Include a tip for an error a user encountered while trying to setup V2

Improve docs and include redirect
